version: '3'

services:

  web:
    build:
      context: ./
      dockerfile: ./packages/web/Dockerfile
    container_name: retdd.web
    restart: always
    depends_on:
      - api
    volumes:
      - ./:/home/node/app
    ports:
      - 8001:8080
    env_file:
      - ./configs/web.env
    stdin_open: true
    command: yarn dev

  api:
    build:
      context: ./
      dockerfile: ./packages/api/Dockerfile
    container_name: retdd.api
    restart: always
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app/packages/api
    ports:
      - 8002:8080
    env_file:
      - ./configs/api.env
    command: yarn dev
