// flow-typed signature: d87d10c64d08197ecb4300c2823b03ac
// flow-typed version: <<STUB>>/eslint-plugin-sort_v2.4.0/flow_v0.188.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-sort'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-sort' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-sort/lib/__mocks__/resolver' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib/resolver' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib/rules/destructuring-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib/rules/export-members' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib/rules/exports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib/rules/import-members' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib/rules/imports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib/rules/object-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib/rules/type-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib/ts-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-sort/lib/__mocks__/resolver.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/__mocks__/resolver'>;
}
declare module 'eslint-plugin-sort/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib'>;
}
declare module 'eslint-plugin-sort/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib'>;
}
declare module 'eslint-plugin-sort/lib/resolver.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/resolver'>;
}
declare module 'eslint-plugin-sort/lib/rules/destructuring-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/rules/destructuring-properties'>;
}
declare module 'eslint-plugin-sort/lib/rules/export-members.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/rules/export-members'>;
}
declare module 'eslint-plugin-sort/lib/rules/exports.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/rules/exports'>;
}
declare module 'eslint-plugin-sort/lib/rules/import-members.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/rules/import-members'>;
}
declare module 'eslint-plugin-sort/lib/rules/imports.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/rules/imports'>;
}
declare module 'eslint-plugin-sort/lib/rules/object-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/rules/object-properties'>;
}
declare module 'eslint-plugin-sort/lib/rules/type-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/rules/type-properties'>;
}
declare module 'eslint-plugin-sort/lib/ts-utils.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/ts-utils'>;
}
declare module 'eslint-plugin-sort/lib/utils.js' {
  declare module.exports: $Exports<'eslint-plugin-sort/lib/utils'>;
}
