// flow-typed signature: 57350c0f5bb0efccc45393db1bd9e462
// flow-typed version: <<STUB>>/eslint-config-problems_v6.0.0/flow_v0.188.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-problems'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-problems' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-problems/internal-eslintrc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-problems/index' {
  declare module.exports: $Exports<'eslint-config-problems'>;
}
declare module 'eslint-config-problems/index.js' {
  declare module.exports: $Exports<'eslint-config-problems'>;
}
declare module 'eslint-config-problems/internal-eslintrc.js' {
  declare module.exports: $Exports<'eslint-config-problems/internal-eslintrc'>;
}
