// flow-typed signature: 7a08b6b661d9e0406f12d982fd897bb0
// flow-typed version: <<STUB>>/jest-coverage-thresholds-bumper_v1.1.0/flow_v0.188.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-coverage-thresholds-bumper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-coverage-thresholds-bumper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-coverage-thresholds-bumper/dist/constants' {
  declare module.exports: any;
}

declare module 'jest-coverage-thresholds-bumper/dist/coverage-thresholds-adapters' {
  declare module.exports: any;
}

declare module 'jest-coverage-thresholds-bumper/dist' {
  declare module.exports: any;
}

declare module 'jest-coverage-thresholds-bumper/dist/jest-config-file-finder' {
  declare module.exports: any;
}

declare module 'jest-coverage-thresholds-bumper/dist/logger' {
  declare module.exports: any;
}

declare module 'jest-coverage-thresholds-bumper/dist/program' {
  declare module.exports: any;
}

declare module 'jest-coverage-thresholds-bumper/dist/program.test' {
  declare module.exports: any;
}

declare module 'jest-coverage-thresholds-bumper/dist/utils' {
  declare module.exports: any;
}

declare module 'jest-coverage-thresholds-bumper/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-coverage-thresholds-bumper/dist/constants.js' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper/dist/constants'>;
}
declare module 'jest-coverage-thresholds-bumper/dist/coverage-thresholds-adapters.js' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper/dist/coverage-thresholds-adapters'>;
}
declare module 'jest-coverage-thresholds-bumper/dist/index' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper/dist'>;
}
declare module 'jest-coverage-thresholds-bumper/dist/index.js' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper/dist'>;
}
declare module 'jest-coverage-thresholds-bumper/dist/jest-config-file-finder.js' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper/dist/jest-config-file-finder'>;
}
declare module 'jest-coverage-thresholds-bumper/dist/logger.js' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper/dist/logger'>;
}
declare module 'jest-coverage-thresholds-bumper/dist/program.js' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper/dist/program'>;
}
declare module 'jest-coverage-thresholds-bumper/dist/program.test.js' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper/dist/program.test'>;
}
declare module 'jest-coverage-thresholds-bumper/dist/utils.js' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper/dist/utils'>;
}
declare module 'jest-coverage-thresholds-bumper/index' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper'>;
}
declare module 'jest-coverage-thresholds-bumper/index.js' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper'>;
}
declare module 'jest-coverage-thresholds-bumper/jest.config.js' {
  declare module.exports: $Exports<'jest-coverage-thresholds-bumper/jest.config'>;
}
